name: mstore
description: A new Flutter package project.
version: 0.0.1
author: hackett<hackettice@gmail.com>
homepage: https://github.com/hackett0/mstore

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter: